ALTER TABLE prompt_cache
    ADD COLUMN cache_scope TEXT NOT NULL DEFAULT 'legacy',
    ADD COLUMN expires_at TIMESTAMPTZ NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '24 hours'),
    ADD COLUMN last_accessed_at TIMESTAMPTZ,
    ADD COLUMN hit_count BIGINT NOT NULL DEFAULT 0;
